Список общих фильмов
Victor99999987/java-filmorate pull request #6
Opened 2023-05-19 09:25 UTC by EvgeniyaLapteva

2023-05-19 12:21 UTC, Victor99999987 requested changes

2023-05-19 12:21 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Запрос на получение списка общих фильмов пользователей id = {} и id = {}", userId, friendId);
Давай фиксировать только некоторые несостыковки, где исключения выбрасываются. Это сервисный слой и хранилище.

2023-05-19 12:21 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final CommonFilmsStorage commonStorage;
Тут лучше сделать интерфейс FilmsStorage, который будет наследовать все от Storage<Film> и дополнится некоторыми плюшками. Для других задач в него же можно добавить что-то недостающее. Здесь же с одним хранилищем связаны две сущьности в одном классе.

2023-05-19 12:21 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Film film : usersFilms) {
Есть такая удобная функция retainAll(Collection c) — удаляет элементы, не принадлежащие переданной коллекции. Посмотри как реализовано в выведении общих друзей. Хотя в данном случае можно обойтись одним запросом к БД.

2023-05-19 16:33 UTC, Victor99999987 approved these changes

2023-05-22 03:56 UTC, IvanPozhidaev approved these changes

2023-05-22 03:57 UTC, merged