Add reviews
Victor99999987/java-filmorate pull request #7
Opened 2023-05-20 11:39 UTC by dima-irqtsk

Вроде всё работает, код подчистил, все тесты проходят. Свои тесты еще не писал.

2023-05-22 03:45 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        findFilm(review.getFilmId());
Может быть вместо методов private void findUser/Film использовать вызов методов getUser/FilmByID из хранилищ DbUser/FilmStorage?

2023-05-22 03:45 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +    public Review createReview(Review review) {
Можно сколько угодно раз добавить отзыв на фильм от одного и того же пользователя

2023-05-22 03:45 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void like(@PathVariable long id, @PathVariable long userId) {
Может быть метод назвать addLike?

2023-05-22 03:45 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void dislike(@PathVariable long id, @PathVariable long userId) {
А этот addDislike

2023-05-22 03:45 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Collection<Review> findAllBiIdFilm(
findAllByIdFilm?

2023-05-22 04:26 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Collection<Review> findAllBiIdFilm(
Да. Спасибо )

2023-05-22 04:27 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        findFilm(review.getFilmId());
Да, была такая мысль. Ща попробую.

2023-05-22 04:58 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        findFilm(review.getFilmId());
Наверное, я смогу найти косяк в коде, но мои методы делают примитивнейший запрос к БД, а методы из хранилищ юзеров и фильмов делают запрос на множество полей с джойнами и потом со сборкой объектов. Может, оставить как есть?

2023-05-22 05:32 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +    public Review createReview(Review review) {
Если честно, я даже не знаю, нужно ли вводить такое ограничение. Ну это типа как разрешить в ВК оставлять не более одного коммента под фоточкой от одного пользователя. 
Ну то есть, можно так сделать, но нужно ли?

2023-05-22 06:34 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        findFilm(review.getFilmId());
Давай оставим твой вариант

2023-05-22 06:34 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +    public Review createReview(Review review) {
Подождем еще одно мнение

2023-05-23 04:52 UTC, Victor99999987 requested changes
Нужно придерживаться структуры проекта, наследование интерфейсов обязательно.

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS reviews_likes CASCADE;
Никаких cascade при удалении таблицы не нужно. Лучше просто поменять строки местами. Сначала удалить таблицу, которая использует поля-зависимости. (порядок такой reviews_likes,reviews,users,films). Создаешь ведь таблицы в некоторой последовательности (связывать же нужно с чем-то)

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new ReviewNotFoundException("Отзыв с ID = " + id + " не найден.");
Эту проверку лучше сделать в методе findById. Там бросать исключение.

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +    public Review createReview(Review review) {
Множество отзывов - хорошо

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        String findAllReviewsByFilm = "SELECT * FROM REVIEWS WHERE FILM_ID = ? " +
Здесь не хватает проверки, что фильм вообще существует.

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        return findReviewById(review.getReviewId()).get();
Выше уже была проверка на успешность операции. Зачем опять в БД лазить за этим отзывом? Мы же оптимизируем нагрузку на БД

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            return Optional.empty();
Лучше выбрасывать исключение, что отзыв не найден

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        String deleteReview = "DELETE FROM REVIEWS WHERE REVIEW_ID = ?";
при удалении нужно проверить, есть вообще объект и вернуть объект, который пох..ли

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении лайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Получается, что один пользователь может ставить много лайков на один и тот же отзыв. Здесь нет проверки на уникальность. В моделе следует сделать set для отзыва, где будут id пользователей

2023-05-23 04:52 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении дизлайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
так же как с лайками

2023-05-23 08:02 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            return Optional.empty();
У меня это исключение выбрасывалось на уровне сервиса, но после переделки репозитория под соответствие общему интерфейсу я перенес это на уровень ниже, да.

2023-05-23 08:04 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        String deleteReview = "DELETE FROM REVIEWS WHERE REVIEW_ID = ?";
Да, когда привел в соответствие с общим интерфейсом, я добавил проверку и возвращаемый объект.

2023-05-23 08:09 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении лайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Нет, база данных не позволяет поставить больше одного лайка от одного пользователя, потому что в таблице `REVIEWS_LIKES` составной ключ — соответственно, может быть только одна уникальная пара значений `REVIEW_ID` и `USER_ID`. И если пользователь поставил лайк, то он уже не может поставить второй лайк.

2023-05-23 08:11 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении дизлайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Ну тут тот же ответ )
Нормально всё работает, ограничение на уровне БД. Не нужно зря усложнять, как мне кажется.

2023-05-23 09:42 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении лайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Попробуй в DBeaver сделать подряд несколько запросов 
INSERT INTO REVIEWS_LIKES (REVIEW_ID, USER_ID, IS_LIKE) VALUES (1,1,true)
все они добавятся
либо нужно запрос менять, либо здесь проверку делать дополнительно

2023-05-24 15:04 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении лайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Добавлены более информативные сообщения в ответ на попытку пользователя поставить более одного лайка на отзыв

2023-05-24 15:04 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +            log.info("Ошибка при добавлении дизлайка для отзыва ID = {} от пользователя с ID = {}.", reviewId, userId);
Добавлены более информативные сообщения в ответ на попытку пользователя поставить более одного дизлайка на отзыв

2023-05-24 16:16 UTC, EvgeniyaLapteva approved these changes

2023-05-25 04:29 UTC, Victor99999987 approved these changes

2023-05-25 04:29 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.remove(id);
Давай вернем объект, который удалили. В хранилище уже все реализовано.
return reviewStorage.remove(id)

2023-05-25 04:29 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        service.delete(id);
Давай вернем объект, который удалили. В хранилище уже все реализовано.
в сервисе чутка переделать и он сюда передавать будет.

2023-05-25 04:29 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbReviewStorage.java
> +        } else {
else условие лишнее. лишние кавычки, лишние строчки (если будет беда, дальше все равно не пойдет).
вообще, jdbcTemplate.update(deleteReview, id) вернет 0, если нету задействованных строчек, но на подобное проверка была выше.
если будет ошибка при выполнении запроса, то это исключение не спасет, нужно весь запрос оборачивать в try-catch

2023-05-25 10:59 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.remove(id);
Готово

2023-05-25 11:00 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        service.delete(id);
Готово

2023-05-25 11:34 UTC, merged