feat: добавить режиссёров в фильмы
Victor99999987/java-filmorate pull request #9
Opened 2023-05-23 03:55 UTC by IvanPozhidaev

2023-05-23 04:43 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиссер с таким id отсутствует в базе");
Ловим исключение — выбрасываем такое же исключение )
Возможно, имеет смысл сделать обработку исключения на уровне хранилища?

2023-05-23 04:45 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/service/ErrorHandler.java
> +        e.printStackTrace();
Да, этого не хватало при обработке исключений. 
Когда выводится только «произошла непредвиденная ошибка» это было очень не информативно.
Здорово, что ты добавил это.

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиссер с таким id отсутствует в базе");
Вообще проверку наличия режиссера в базе вижу уже на уровне класса DbDirectorStorage, нужна ли она и тут?

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +//        if (director.getId() != null) {
Закомментированные строки лучше удалить - даже если у режиссера при создании будет id, наш метод присвоит ему id сам

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        Integer count = jdbcTemplate.queryForObject("SELECT count(DIRECTOR_ID) FROM DIRECTORS WHERE DIRECTOR_ID = ?",
Может быть, проверку на наличие режиссера в базе лучше сделать методом getById этого же класса? И лишний код не писать, и логирование там есть. Либо на уровне выбрасывания ошибки логирование добавить

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        String sqlQuery = "INSERT INTO directors (name) VALUES (?)";
Можно сколько угодно раз создать режиссера с одним и тем же именем. Нужны ли нам дубли в базе?

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +public class DbFilmStorage extends DbStorage implements Storage<Film>, FilmStorage {
Тут достаточно будет public class DbFilmStorage extends DbStorage implements FilmStorage, у тебя же FilmStorage extends Storage<Film>

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +        Set<Director> directors = film.getDirectors();
Если при создании фильма укажем в его списке режиссера, который не внесен в базу, фильм сохранится без режиссера и не возникнет ошибки о том, что такого режиссера нет в базе данных.

2023-05-23 06:23 UTC, EvgeniyaLapteva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +    public List<Film> findFilmsSortByLikesAndYear(Long directorId, String param) {
В этом методе общую часть sql запроса можно вынести до оператора switch, а в вариантах, которые он перечисляет с помощью конкатенации добавлять нужные строки в sql-запрос. Так код значительно сократится

2023-05-23 07:01 UTC, Victor99999987 requested changes

2023-05-23 07:01 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        jdbcTemplate.update("DELETE FROM film_director WHERE director_id = ?", id);
этот запрос лишний. добавляем каскад при создании таблицы и когда удалим директора, удалятся и все связи.

2023-05-23 07:15 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +            for (Director director : directors) {
Здесь много обращений к БД. Лучше сделать через batchUpdate. За одно обращение к БД внесем всех директоров.

2023-05-23 07:15 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +        Set<Director> directors = film.getDirectors();
Действительно, лучше проверить есть ли такие вообще режиссеры

2023-05-23 07:15 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +                        film.getId(), director.getId());
Здесь тоже через batchUpdate следует сделать

2023-05-23 08:45 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Optional<Director> optionalDirector = Optional.ofNullable(directorStorage.getById(id));
Убрана проверка.

2023-05-23 08:46 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиссер не найден!");
Убрал.

2023-05-23 08:48 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/service/ErrorHandler.java
> +        e.printStackTrace();
Когда дебажил, тоже не хватало. Потому и добавил.

2023-05-23 08:49 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +//        if (director.getId() != null) {
Убрал закомментированные строки.

2023-05-23 08:53 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        jdbcTemplate.update("DELETE FROM film_director WHERE director_id = ?", id);
Добавлены каскады, лишний запрос убран.

2023-05-23 08:54 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +public class DbFilmStorage extends DbStorage implements Storage<Film>, FilmStorage {
Убрал лишнюю имплементацию.

2023-05-23 11:10 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        String sqlQuery = "INSERT INTO directors (name) VALUES (?)";
Добавил проверку на дублирование.

2023-05-23 13:32 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиссер с таким id отсутствует в базе");
Убрана лишняя проверка

2023-05-23 13:48 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        jdbcTemplate.update("DELETE FROM film_director WHERE director_id = ?", id);
При добавлении каскадов в схему и удалении этого запроса к базе из хранилища валятся тесты мавена на гитхабе.

2023-05-24 11:09 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +        Integer count = jdbcTemplate.queryForObject("SELECT count(DIRECTOR_ID) FROM DIRECTORS WHERE DIRECTOR_ID = ?",
Вынес данный код в отдельный метод

2023-05-24 11:34 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorage.java
> +                        film.getId(), director.getId());
Сделано через batchUpdate

2023-05-24 14:41 UTC, Victor99999987 approved these changes

2023-05-24 14:41 UTC, Victor99999987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbDirectorStorage.java
> +            long id = jdbcTemplate.queryForObject(sqlSelectIdQuery, Long.class, director.getName());
лучше тут выбрасывать исключение, что такой уже есть.

2023-05-24 15:07 UTC, merged